name: Go

on:
  push:
    tags:
      - v**

jobs:
  build:
    strategy:
      matrix:
        target: [
          {
            "GOOS": "linux",
            "GOARCH": "amd64",
            "NAME": "whatsapp-client-linux-amd64",
          },
          {
            "GOOS": "linux",
            "GOARCH": "arm64",
            "NAME": "whatsapp-client-linux-arm64",
          },
          {
            "GOOS": "darwin",
            "GOARCH": "amd64",
            "NAME": "whatsapp-client-darwin-amd64",
          },
          {
            "GOOS": "darwin",
            "GOARCH": "arm64",
            "NAME": "whatsapp-client-darwin-arm64",
          },
          {
            "GOOS": "windows",
            "GOARCH": "amd64",
            "NAME": "whatsapp-client-windows-amd64.exe",
          },
        ]
    env:
      LDFLAGS: "-X 'main.version=${{ github.ref_name }}' -X 'main.commitID=${{ github.sha }}' -X 'main.buildTime=${{ github.event.head_commit.timestamp }}' -w -s"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true

      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: Build
        run: |
          mkdir -p bin
          GOOS=${{ matrix.target.GOOS }} GOARCH=${{ matrix.target.GOARCH }} go build -ldflags "${{ env.LDFLAGS }}" -o bin/${{ matrix.target.NAME }} main.go

      - name: Run UPX (exclude darwin)
        if: matrix.target.GOOS != 'darwin'
        uses: crazy-max/ghaction-upx@v1
        with:
          version: latest
          files: ./bin/*
          args: -fq

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/*
          draft: true
