name: Go

on:
  push:
    tags:
      - v**

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      PROJECT_NAME: whatsapp-client
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Build
        env:
          CGO_ENABLED: 1
        run: |
          go build -ldflags "-X 'main.version=${{ github.ref }}' -X 'main.commitID=${{ github.sha }}' -X 'main.buildTime=${{ github.event.head_commit.timestamp }}'" -o ./dist/${{ env.PROJECT_NAME }} main.go

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1
        with:
          version: latest
          files: ./dist/*
          args: -fq     

      - name: Package (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd dist
          tar -czvf whatsapp-client.tar.gz ${{ env.PROJECT_NAME }}
          rm ${{ env.PROJECT_NAME }}

      - name: Package (windows-latest)
        if: matrix.os == 'windows-latest'
        run: |
          Set-Location -Path dist
          Rename-Item -Path ${{ env.PROJECT_NAME }} -NewName ${{ env.PROJECT_NAME }}.exe
          Compress-Archive -Path ${{ env.PROJECT_NAME }}.exe -DestinationPath whatsapp-client.zip
          rm ${{ env.PROJECT_NAME }}.exe

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          draft: true
