name: Go

on:
  push:
    tags:
      - v**

jobs:
  build:
    env:
      NAME: whatsapp-client
      LDFLAGS: "-X 'main.version=${{ github.ref }}' -X 'main.commitID=${{ github.sha }}' -X 'main.buildTime=${{ github.event.head_commit.timestamp }}'"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true

      - name: Set up xgo
        run: |
          docker pull techknowlogick/xgo:latest
          go install src.techknowlogick.com/xgo@latest

      - name: Build by xgo
        run: |
          mkdir bin
          xgo --targets="windows/*,darwin-10.16/*" -ldflags="${LDFLAGS}" --out bin/${{ env.NAME }} . 
      
      - name: Rename
        run: |
          mv bin/${{ env.NAME }}-windows-4.0-386.exe bin/${{ env.NAME }}-386.exe
          mv bin/${{ env.NAME }}-windows-4.0-amd64.exe bin/${{ env.NAME }}-amd64.exe
          mv bin/${{ env.NAME }}-darwin-10.16-amd64 bin/${{ env.NAME }}-darwin-amd64
          mv bin/${{ env.NAME }}-darwin-10.16-arm64 bin/${{ env.NAME }}-darwin-arm64
    
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1
        with:
          version: latest
          files: ./bin/*
          args: -fq

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/*
          draft: true
